---
name: Submodule Updates

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master, main]
  workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'Formula-Electric-Belgium/DV_Autonomous_System'
      CHECKOUT_BRANCH: 'develop'
      PR_AGAINST_BRANCH: 'develop'
      OWNER: 'Formula-Electric-Belgium'
      REVIEWERS: "['MauritsVM']"

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: Formula-Electric-Belgium/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.SECRET }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          reviewer: ${{ env.REVIEWERS }}
          owner: ${{ env.OWNER }}